name: BillCostApp WorkFlow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Build and Push Docker Image to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: |
              atulchan/billcost_app_frontend:${{ github.sha }}

        - name: SSH into AWS Instance and Update Docker Container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ${{ secrets.AWS_USERNAME }}
            key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
            script: |
              docker stop billcost_app_frontend
              docker rm billcost_app_frontend
              previous_image_id=$(docker images --format "{{.ID}}" atulchan/billcost_app_frontend)
              if [ -n "$previous_image_id" ]; then
              docker rmi "$previous_image_id"
              fi
              docker pull atulchan/billcost_app_backend:${{ github.sha }}
              docker run -d -p 443:443 --name billcost_app_frontend atulchan/billcost_app_frontend:${{ github.sha }} 

    
